name: .NET CI/CD Classlib

on:
  push:

jobs:
  call-build:
    uses: ./.github/workflows/reusable-ci-dotnet.yaml
    with:
      app-path: ./src-dotnet-classlib

  deploy: 
    runs-on: ubuntu-latest      
    steps: 
      - run: echo "teste"

    # - name: Pack
    #   run: dotnet pack ./src-dotnet-classlib --no-build --configuration Release --output ./nupkg

    # - name: Publish to GitHub Packages
    #   run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/andrediasbr/index.json