name: CI/CD Java Class Library

on:
  push:

jobs:
  call-build:
    uses: ./.github/workflows/reusable-ci-java.yaml
    with:
      app-path: ./src-java-classlib
      
  deploy:
    needs: call-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ./output

    # - name: Publish to GitHub Packages
    #   run: mvn deploy:deploy-file -Dfile=./output/your-artifact.jar -DgroupId=com.yourcompany -DartifactId=your-artifact -Dversion=1.0.0 -Dpackaging=jar -DrepositoryId=github -Durl=https://maven.pkg.github.com/your-repo
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   working-directory: ./output