name: .NET CI/CD WebApi

on:
  push:

jobs:
  build:
    uses: ./.github/workflows/reusable-ci-dotnet.yaml
    with:
      app-path: ./src-dotnet-webapi

    # - name: Publish
    #   run: dotnet publish ./src-dotnet-webapi --no-build --configuration Release --output ./output