name: .NET CI/CD Classlib

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
          dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src-dotnet-classlib

    - name: Build
      run: dotnet build ./src-dotnet-classlib --no-restore --configuration Release

    - name: Test
      run: dotnet test ./src-dotnet-classlib --no-build --verbosity normal --configuration Release

    - name: Pack
      run: dotnet pack ./src-dotnet-classlib --no-build --configuration Release --output ./nupkg

    # - name: Publish to GitHub Packages
    #   run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/andrediasbr/index.json