name: .NET CI/CD WebApi

on:
  push:

jobs:
  call-build:
    uses: ./.github/workflows/reusable-ci-dotnet.yaml
    with:
      app-path: ./src-dotnet-webapi
      package-type: "publish"

  deploy: 
    needs: call-build
    runs-on: ubuntu-latest      
    steps: 
      - run: echo "teste"
    
