name: .NET CI/CD Classlib

on:
  push:

jobs:
  call-build:
    uses: ./.github/workflows/reusable-ci-dotnet.yaml
    with:
      app-path: ./src-dotnet-classlib
      package-type: "package"

  deploy: 
    needs: call-build
    runs-on: ubuntu-latest      
    permissions: 
      contents: read
      packages: write
    steps: 

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./output

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/andrediasbr/index.json