name: .NET CI/CD WebApi

on:
  push:

jobs:
  call-build:
    uses: ./.github/workflows/reusable-ci-dotnet.yaml
    with:
      app-path: ./src-dotnet-webapi

  deploy: 
    runs-on: ubuntu-latest      
    steps: 
      - run: echo "teste"
    
      # - name: Publish
    #   run: dotnet publish ./src-dotnet-webapi --no-build --configuration Release --output ./output