name: .NET CI Reusable

on:
  workflow_call: 
    inputs:
      app-path: 
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
          dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.app-path }}

    - name: Build
      run: dotnet build ${{ inputs.app-path }} --no-restore --configuration Release

    - name: Test
      run: dotnet test ${{ inputs.app-path }} --no-build --verbosity normal --configuration Release

    